/* Generated with cbindgen:0.13.0 */

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <cstdarg>
#include <cstdint>
#include <cstdlib>
#include <new>

extern "C" {

void get_image_vector_rs(const uint8_t *ptr, uint32_t width, uint32_t height);

void write_small_image_rs();

} // extern "C"
