/* Generated with cbindgen:0.13.0 */

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <cstdarg>
#include <cstdint>
#include <cstdlib>
#include <new>

static const uint32_t TEN_U32 = 10;

struct LargeArray {
    uint32_t boxed_array[10000];
};

using Pixel = uint8_t[3];

extern "C" {

void get_raw_pointer(const uint8_t *ptr);

void hello_from_rust();

int32_t return_a_four();

} // extern "C"
